const String GoogleSignInViewRoute = "GoogleSignInView";
const String PasswordViewRoute = "PasswordView";
const String HomeViewRoute = "HomeView";
const String CreateEventRoute = "CreateEvent";
const String ViewEventRoute = "ViewEvent";
const String CreateResourceRoute = "CreateResource";
const String ViewResourceRoute = "ViewResource";
const String AddMembersRoute = "AddMembers";
const String AddImageRoute = "AddImages";
// Generate the views here
